// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Partify.Persistence;

#nullable disable

namespace Partify.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919131928_AddSpotifyTokens")]
    partial class AddSpotifyTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive_collation", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Partify.Domain.Entities.SpotifyTokens", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(22)
                        .HasColumnType("character(22)")
                        .IsFixedLength();

                    b.Property<string>("AccessToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("AccessTokenExpiresOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("UserId");

                    b.ToTable("SpotifyTokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
